// Code generated by MockGen. DO NOT EDIT.
// Source: article_handler.go
//
// Generated by this command:
//
//	mockgen -destination mock/article_mock.go -source article_handler.go ArticleHandler
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleHandler is a mock of ArticleHandler interface.
type MockArticleHandler struct {
	ctrl     *gomock.Controller
	recorder *MockArticleHandlerMockRecorder
	isgomock struct{}
}

// MockArticleHandlerMockRecorder is the mock recorder for MockArticleHandler.
type MockArticleHandlerMockRecorder struct {
	mock *MockArticleHandler
}

// NewMockArticleHandler creates a new mock instance.
func NewMockArticleHandler(ctrl *gomock.Controller) *MockArticleHandler {
	mock := &MockArticleHandler{ctrl: ctrl}
	mock.recorder = &MockArticleHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleHandler) EXPECT() *MockArticleHandlerMockRecorder {
	return m.recorder
}

// ArticleCommentCreate mocks base method.
func (m *MockArticleHandler) ArticleCommentCreate(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleCommentCreate", c)
}

// ArticleCommentCreate indicates an expected call of ArticleCommentCreate.
func (mr *MockArticleHandlerMockRecorder) ArticleCommentCreate(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleCommentCreate", reflect.TypeOf((*MockArticleHandler)(nil).ArticleCommentCreate), c)
}

// ArticleCommentDelete mocks base method.
func (m *MockArticleHandler) ArticleCommentDelete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleCommentDelete", c)
}

// ArticleCommentDelete indicates an expected call of ArticleCommentDelete.
func (mr *MockArticleHandlerMockRecorder) ArticleCommentDelete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleCommentDelete", reflect.TypeOf((*MockArticleHandler)(nil).ArticleCommentDelete), c)
}

// ArticleCommentList mocks base method.
func (m *MockArticleHandler) ArticleCommentList(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleCommentList", c)
}

// ArticleCommentList indicates an expected call of ArticleCommentList.
func (mr *MockArticleHandlerMockRecorder) ArticleCommentList(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleCommentList", reflect.TypeOf((*MockArticleHandler)(nil).ArticleCommentList), c)
}

// ArticleCreate mocks base method.
func (m *MockArticleHandler) ArticleCreate(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleCreate", c)
}

// ArticleCreate indicates an expected call of ArticleCreate.
func (mr *MockArticleHandlerMockRecorder) ArticleCreate(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleCreate", reflect.TypeOf((*MockArticleHandler)(nil).ArticleCreate), c)
}

// ArticleDelete mocks base method.
func (m *MockArticleHandler) ArticleDelete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleDelete", c)
}

// ArticleDelete indicates an expected call of ArticleDelete.
func (mr *MockArticleHandlerMockRecorder) ArticleDelete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleDelete", reflect.TypeOf((*MockArticleHandler)(nil).ArticleDelete), c)
}

// ArticleFavorite mocks base method.
func (m *MockArticleHandler) ArticleFavorite(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleFavorite", c)
}

// ArticleFavorite indicates an expected call of ArticleFavorite.
func (mr *MockArticleHandlerMockRecorder) ArticleFavorite(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleFavorite", reflect.TypeOf((*MockArticleHandler)(nil).ArticleFavorite), c)
}

// ArticleFeed mocks base method.
func (m *MockArticleHandler) ArticleFeed(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleFeed", c)
}

// ArticleFeed indicates an expected call of ArticleFeed.
func (mr *MockArticleHandlerMockRecorder) ArticleFeed(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleFeed", reflect.TypeOf((*MockArticleHandler)(nil).ArticleFeed), c)
}

// ArticleList mocks base method.
func (m *MockArticleHandler) ArticleList(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleList", c)
}

// ArticleList indicates an expected call of ArticleList.
func (mr *MockArticleHandlerMockRecorder) ArticleList(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleList", reflect.TypeOf((*MockArticleHandler)(nil).ArticleList), c)
}

// ArticleRetrieve mocks base method.
func (m *MockArticleHandler) ArticleRetrieve(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleRetrieve", c)
}

// ArticleRetrieve indicates an expected call of ArticleRetrieve.
func (mr *MockArticleHandlerMockRecorder) ArticleRetrieve(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleRetrieve", reflect.TypeOf((*MockArticleHandler)(nil).ArticleRetrieve), c)
}

// ArticleUnfavorite mocks base method.
func (m *MockArticleHandler) ArticleUnfavorite(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleUnfavorite", c)
}

// ArticleUnfavorite indicates an expected call of ArticleUnfavorite.
func (mr *MockArticleHandlerMockRecorder) ArticleUnfavorite(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleUnfavorite", reflect.TypeOf((*MockArticleHandler)(nil).ArticleUnfavorite), c)
}

// ArticleUpdate mocks base method.
func (m *MockArticleHandler) ArticleUpdate(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ArticleUpdate", c)
}

// ArticleUpdate indicates an expected call of ArticleUpdate.
func (mr *MockArticleHandlerMockRecorder) ArticleUpdate(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleUpdate", reflect.TypeOf((*MockArticleHandler)(nil).ArticleUpdate), c)
}

// TagList mocks base method.
func (m *MockArticleHandler) TagList(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TagList", c)
}

// TagList indicates an expected call of TagList.
func (mr *MockArticleHandlerMockRecorder) TagList(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagList", reflect.TypeOf((*MockArticleHandler)(nil).TagList), c)
}
