// Code generated by MockGen. DO NOT EDIT.
// Source: user_handler.go
//
// Generated by this command:
//
//	mockgen -destination mock/users_mock.go -source user_handler.go UsersHandler
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersHandler is a mock of UsersHandler interface.
type MockUsersHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUsersHandlerMockRecorder
	isgomock struct{}
}

// MockUsersHandlerMockRecorder is the mock recorder for MockUsersHandler.
type MockUsersHandlerMockRecorder struct {
	mock *MockUsersHandler
}

// NewMockUsersHandler creates a new mock instance.
func NewMockUsersHandler(ctrl *gomock.Controller) *MockUsersHandler {
	mock := &MockUsersHandler{ctrl: ctrl}
	mock.recorder = &MockUsersHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersHandler) EXPECT() *MockUsersHandlerMockRecorder {
	return m.recorder
}

// ProfileFollow mocks base method.
func (m *MockUsersHandler) ProfileFollow(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProfileFollow", c)
}

// ProfileFollow indicates an expected call of ProfileFollow.
func (mr *MockUsersHandlerMockRecorder) ProfileFollow(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileFollow", reflect.TypeOf((*MockUsersHandler)(nil).ProfileFollow), c)
}

// ProfileRetrieve mocks base method.
func (m *MockUsersHandler) ProfileRetrieve(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProfileRetrieve", c)
}

// ProfileRetrieve indicates an expected call of ProfileRetrieve.
func (mr *MockUsersHandlerMockRecorder) ProfileRetrieve(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileRetrieve", reflect.TypeOf((*MockUsersHandler)(nil).ProfileRetrieve), c)
}

// ProfileUnfollow mocks base method.
func (m *MockUsersHandler) ProfileUnfollow(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProfileUnfollow", c)
}

// ProfileUnfollow indicates an expected call of ProfileUnfollow.
func (mr *MockUsersHandlerMockRecorder) ProfileUnfollow(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileUnfollow", reflect.TypeOf((*MockUsersHandler)(nil).ProfileUnfollow), c)
}

// UserRetrieve mocks base method.
func (m *MockUsersHandler) UserRetrieve(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UserRetrieve", c)
}

// UserRetrieve indicates an expected call of UserRetrieve.
func (mr *MockUsersHandlerMockRecorder) UserRetrieve(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRetrieve", reflect.TypeOf((*MockUsersHandler)(nil).UserRetrieve), c)
}

// UserUpdate mocks base method.
func (m *MockUsersHandler) UserUpdate(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UserUpdate", c)
}

// UserUpdate indicates an expected call of UserUpdate.
func (mr *MockUsersHandlerMockRecorder) UserUpdate(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserUpdate", reflect.TypeOf((*MockUsersHandler)(nil).UserUpdate), c)
}

// UsersLogin mocks base method.
func (m *MockUsersHandler) UsersLogin(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UsersLogin", c)
}

// UsersLogin indicates an expected call of UsersLogin.
func (mr *MockUsersHandlerMockRecorder) UsersLogin(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersLogin", reflect.TypeOf((*MockUsersHandler)(nil).UsersLogin), c)
}

// UsersRegistration mocks base method.
func (m *MockUsersHandler) UsersRegistration(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UsersRegistration", c)
}

// UsersRegistration indicates an expected call of UsersRegistration.
func (mr *MockUsersHandlerMockRecorder) UsersRegistration(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersRegistration", reflect.TypeOf((*MockUsersHandler)(nil).UsersRegistration), c)
}
