// Code generated by MockGen. DO NOT EDIT.
// Source: article.go
//
// Generated by this command:
//
//	mockgen -destination mock/article_repo_mock.go -source article.go ArticleRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	repository "com/realworld/ginrxgogorm/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockArticleRepository) Delete(condition any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockArticleRepositoryMockRecorder) Delete(condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockArticleRepository)(nil).Delete), condition)
}

// FavoriteBy mocks base method.
func (m *MockArticleRepository) FavoriteBy(article repository.ArticleModel, articleUser repository.ArticleUserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FavoriteBy", article, articleUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// FavoriteBy indicates an expected call of FavoriteBy.
func (mr *MockArticleRepositoryMockRecorder) FavoriteBy(article, articleUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteBy", reflect.TypeOf((*MockArticleRepository)(nil).FavoriteBy), article, articleUser)
}

// FavoritesCount mocks base method.
func (m *MockArticleRepository) FavoritesCount(article repository.ArticleModel) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FavoritesCount", article)
	ret0, _ := ret[0].(uint)
	return ret0
}

// FavoritesCount indicates an expected call of FavoritesCount.
func (mr *MockArticleRepositoryMockRecorder) FavoritesCount(article any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoritesCount", reflect.TypeOf((*MockArticleRepository)(nil).FavoritesCount), article)
}

// FindManyArticle mocks base method.
func (m *MockArticleRepository) FindManyArticle(tag, author, limit, offset, favorited string) ([]repository.ArticleModel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindManyArticle", tag, author, limit, offset, favorited)
	ret0, _ := ret[0].([]repository.ArticleModel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindManyArticle indicates an expected call of FindManyArticle.
func (mr *MockArticleRepositoryMockRecorder) FindManyArticle(tag, author, limit, offset, favorited any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindManyArticle", reflect.TypeOf((*MockArticleRepository)(nil).FindManyArticle), tag, author, limit, offset, favorited)
}

// FindOneArticle mocks base method.
func (m *MockArticleRepository) FindOneArticle(condition any) (repository.ArticleModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneArticle", condition)
	ret0, _ := ret[0].(repository.ArticleModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneArticle indicates an expected call of FindOneArticle.
func (mr *MockArticleRepositoryMockRecorder) FindOneArticle(condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneArticle", reflect.TypeOf((*MockArticleRepository)(nil).FindOneArticle), condition)
}

// GatherLoginUserStat mocks base method.
func (m *MockArticleRepository) GatherLoginUserStat(arg0 repository.ArticleUserModel, arg1 repository.ArticleModel) (bool, bool, uint, repository.ArticleModel) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GatherLoginUserStat", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(uint)
	ret3, _ := ret[3].(repository.ArticleModel)
	return ret0, ret1, ret2, ret3
}

// GatherLoginUserStat indicates an expected call of GatherLoginUserStat.
func (mr *MockArticleRepositoryMockRecorder) GatherLoginUserStat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GatherLoginUserStat", reflect.TypeOf((*MockArticleRepository)(nil).GatherLoginUserStat), arg0, arg1)
}

// GetAllTags mocks base method.
func (m *MockArticleRepository) GetAllTags() ([]repository.TagModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags")
	ret0, _ := ret[0].([]repository.TagModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockArticleRepositoryMockRecorder) GetAllTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockArticleRepository)(nil).GetAllTags))
}

// GetArticleFeed mocks base method.
func (m *MockArticleRepository) GetArticleFeed(self repository.ArticleUserModel, limit, offset string) ([]repository.ArticleModel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleFeed", self, limit, offset)
	ret0, _ := ret[0].([]repository.ArticleModel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArticleFeed indicates an expected call of GetArticleFeed.
func (mr *MockArticleRepositoryMockRecorder) GetArticleFeed(self, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleFeed", reflect.TypeOf((*MockArticleRepository)(nil).GetArticleFeed), self, limit, offset)
}

// GetArticleUserModel mocks base method.
func (m *MockArticleRepository) GetArticleUserModel(userModel repository.UserModel) repository.ArticleUserModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleUserModel", userModel)
	ret0, _ := ret[0].(repository.ArticleUserModel)
	return ret0
}

// GetArticleUserModel indicates an expected call of GetArticleUserModel.
func (mr *MockArticleRepositoryMockRecorder) GetArticleUserModel(userModel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleUserModel", reflect.TypeOf((*MockArticleRepository)(nil).GetArticleUserModel), userModel)
}

// GetComments mocks base method.
func (m *MockArticleRepository) GetComments(self *repository.ArticleModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", self)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetComments indicates an expected call of GetComments.
func (mr *MockArticleRepositoryMockRecorder) GetComments(self any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockArticleRepository)(nil).GetComments), self)
}

// IsFavoriteBy mocks base method.
func (m *MockArticleRepository) IsFavoriteBy(article repository.ArticleModel, articleUser repository.ArticleUserModel) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFavoriteBy", article, articleUser)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFavoriteBy indicates an expected call of IsFavoriteBy.
func (mr *MockArticleRepositoryMockRecorder) IsFavoriteBy(article, articleUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavoriteBy", reflect.TypeOf((*MockArticleRepository)(nil).IsFavoriteBy), article, articleUser)
}

// SaveOne mocks base method.
func (m *MockArticleRepository) SaveOne(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOne", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOne indicates an expected call of SaveOne.
func (mr *MockArticleRepositoryMockRecorder) SaveOne(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOne", reflect.TypeOf((*MockArticleRepository)(nil).SaveOne), data)
}

// SetTags mocks base method.
func (m *MockArticleRepository) SetTags(model *repository.ArticleModel, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTags", model, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTags indicates an expected call of SetTags.
func (mr *MockArticleRepositoryMockRecorder) SetTags(model, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockArticleRepository)(nil).SetTags), model, tags)
}

// UnfavoriteBy mocks base method.
func (m *MockArticleRepository) UnfavoriteBy(article repository.ArticleModel, articleUser repository.ArticleUserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfavoriteBy", article, articleUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfavoriteBy indicates an expected call of UnfavoriteBy.
func (mr *MockArticleRepositoryMockRecorder) UnfavoriteBy(article, articleUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfavoriteBy", reflect.TypeOf((*MockArticleRepository)(nil).UnfavoriteBy), article, articleUser)
}

// Update mocks base method.
func (m *MockArticleRepository) Update(model *repository.ArticleModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArticleRepositoryMockRecorder) Update(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArticleRepository)(nil).Update), model)
}
