// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -destination mock/users_repo_mock.go -source user.go UsersRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	repository "com/realworld/ginrxgogorm/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsersRepository is a mock of UsersRepository interface.
type MockUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepositoryMockRecorder
	isgomock struct{}
}

// MockUsersRepositoryMockRecorder is the mock recorder for MockUsersRepository.
type MockUsersRepositoryMockRecorder struct {
	mock *MockUsersRepository
}

// NewMockUsersRepository creates a new mock instance.
func NewMockUsersRepository(ctrl *gomock.Controller) *MockUsersRepository {
	mock := &MockUsersRepository{ctrl: ctrl}
	mock.recorder = &MockUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepository) EXPECT() *MockUsersRepositoryMockRecorder {
	return m.recorder
}

// FindOneUser mocks base method.
func (m *MockUsersRepository) FindOneUser(refUser repository.UserModel) (repository.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneUser", refUser)
	ret0, _ := ret[0].(repository.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneUser indicates an expected call of FindOneUser.
func (mr *MockUsersRepositoryMockRecorder) FindOneUser(refUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneUser", reflect.TypeOf((*MockUsersRepository)(nil).FindOneUser), refUser)
}

// FindOneUserById mocks base method.
func (m *MockUsersRepository) FindOneUserById(id uint) (repository.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneUserById", id)
	ret0, _ := ret[0].(repository.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneUserById indicates an expected call of FindOneUserById.
func (mr *MockUsersRepositoryMockRecorder) FindOneUserById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneUserById", reflect.TypeOf((*MockUsersRepository)(nil).FindOneUserById), id)
}

// Following mocks base method.
func (m *MockUsersRepository) Following(u, v repository.UserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Following", u, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Following indicates an expected call of Following.
func (mr *MockUsersRepositoryMockRecorder) Following(u, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Following", reflect.TypeOf((*MockUsersRepository)(nil).Following), u, v)
}

// GetFollowings mocks base method.
func (m *MockUsersRepository) GetFollowings(u repository.UserModel) ([]repository.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowings", u)
	ret0, _ := ret[0].([]repository.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowings indicates an expected call of GetFollowings.
func (mr *MockUsersRepositoryMockRecorder) GetFollowings(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowings", reflect.TypeOf((*MockUsersRepository)(nil).GetFollowings), u)
}

// IsFollowings mocks base method.
func (m *MockUsersRepository) IsFollowings(u, v repository.UserModel) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowings", u, v)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowings indicates an expected call of IsFollowings.
func (mr *MockUsersRepositoryMockRecorder) IsFollowings(u, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowings", reflect.TypeOf((*MockUsersRepository)(nil).IsFollowings), u, v)
}

// SaveOne mocks base method.
func (m *MockUsersRepository) SaveOne(data repository.UserModel) (repository.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOne", data)
	ret0, _ := ret[0].(repository.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOne indicates an expected call of SaveOne.
func (mr *MockUsersRepositoryMockRecorder) SaveOne(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOne", reflect.TypeOf((*MockUsersRepository)(nil).SaveOne), data)
}

// Unfollowing mocks base method.
func (m *MockUsersRepository) Unfollowing(u, v repository.UserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollowing", u, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollowing indicates an expected call of Unfollowing.
func (mr *MockUsersRepositoryMockRecorder) Unfollowing(u, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollowing", reflect.TypeOf((*MockUsersRepository)(nil).Unfollowing), u, v)
}

// Update mocks base method.
func (m *MockUsersRepository) Update(model, data repository.UserModel) (repository.UserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", model, data)
	ret0, _ := ret[0].(repository.UserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsersRepositoryMockRecorder) Update(model, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsersRepository)(nil).Update), model, data)
}
